# Generated by Django 5.0.6 on 2024-05-13 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Used to store the titleof the  blog.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Blog unique slug.', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Description about the blog.')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Blog publishing date.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Blog edited date.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Denotes the status of the blog. If false, denotes blog is currently unavailable.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
